# https://taskfile.dev

version: '3'

tasks:

  gomod:
    desc: update go mod
    cmds:
      - go mod tidy

  gofmt:
    cmds:
      - command -v goimports || go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  golint:
    cmds:
      - command -v golangci-lint || go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.13.1
      - golangci-lint run -v ./...

  govulncheck:
    desc: vulnerability detection
    cmds:
      - command -v govulncheck || go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  gci:
    cmds:
      - command -v gci || go install github.com/daixiang0/gci@latest
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/ysicing/spot)" -s default -s blank -s dot .

  lint:
    cmds:
      - task: gofmt
      - task: golint
      - task: govulncheck
      - task: gci

  fmt:
    cmds:
      - task: gomod
      - task: gofmt
      - task: golint
      - task: gci

  snapshot:
    desc: Build Snapshot
    cmds:
      - task: clean
      - command -v goreleaser || go install github.com/goreleaser/goreleaser/v2@latest
      - goreleaser release --snapshot --clean

  clean:
    desc: Clean Up Build Cache Files
    cmds:
      - rm -rf dist

  default:
    cmds:
      - task: snapshot
